module Creestal
  module Core
    class Builder
      def initialize(@ctx : Core::Context, site : Site? = nil)
        @site = site || Site.new(@ctx)
      end

      # Full build — cleans the output directory then delegates entirely to Site.
      # Returns the populated Site so callers can pass it into run_incremental.
      def run : Site
        result = @site.full_sync_result
        validate_output_collisions
        Utils::FS.cleanup_dir(@ctx.site_output) if Dir.exists?(@ctx.site_output)
        Utils::FS.ensure_dir(@ctx.site_output)
        apply(result)
        @site
      end

      # Incremental build — syncs every file in the batch and returns the live Site
      # so the caller (serve) can pass it back on the next change.
      def run_incremental(changed_files : Array(String)) : Site
        result = SyncResult.new
        changed_files.each do |path|
          result.merge!(@site.sync(path))
        end
        validate_output_collisions
        apply(result)
        @site
      end

      private def validate_output_collisions : Nil
        validate_page_output_collisions
        validate_asset_output_collisions
      end

      private def validate_page_output_collisions : Nil
        pages_by_output = @site.pages.values.group_by(&.output_path)
        pages_by_output.each do |output_path, pages|
          next if pages.size < 2

          sources = pages.map(&.entry.relative_path).sort.join(", ")
          raise Errors::PageOutputPathCollisionError.new("Page output path collision: '#{output_path}' generated by #{sources}")
        end
      end

      private def validate_asset_output_collisions : Nil
        assets_by_output = @site.assets.values.group_by do |asset|
          Utils::FS.asset_output_path(asset.relative_path)
        end

        assets_by_output.each do |output_path, assets|
          next if assets.size < 2

          sources = assets.map(&.relative_path).sort.join(", ")
          raise Errors::AssetOutputPathCollisionError.new("Asset output path collision: 'assets/#{output_path}' generated by #{sources}")
        end
      end

      private def apply(result : SyncResult) : Nil
        result.assets_to_copy.each do |asset_path|
          asset = @site.assets[asset_path]? || next
          build_asset(asset)
        end

        result.pages_to_render.each do |page_path|
          page = @site.pages[page_path]? || next
          if page.front_matter.draft
            # Remove any previously built output so the page is no longer served.
            output_path = File.join(@ctx.site_output, page.output_path)
            File.delete(output_path) if File.exists?(output_path)
            next
          end
          build_page(page)
        end

        result.ignored_paths.each do |ignored_path|
          puts "File #{ignored_path} is out of bounds, skipping"
        end
      end

      private def build_asset(asset : FileEntry)
        output_path = File.join(@ctx.assets_out_path, Utils::FS.asset_output_path(asset.relative_path))
        Utils::FS.ensure_dir(File.dirname(output_path))
        Utils::FS.copy_file(asset.full_path, output_path)
      end

      private def build_page(page : Resources::Page)
        output_path = File.join(@ctx.site_output, page.output_path)
        Utils::FS.ensure_dir(File.dirname(output_path))
        layout_path = page.depends_on.first? || raise Errors::MissingLayoutDependencyError.new("Page '#{page.entry.relative_path}' has no layout dependency")
        layout = @site.layouts[layout_path]? || raise Errors::LayoutNotFoundError.new("Layout not found: #{layout_path}")
        page_content = layout.output_content(page, @site.graph)
        Utils::FS.write_file(output_path, page_content)
      end
    end
  end
end
